In [16]:
import numpy as np
import pandas as pd

# Load data
data=pd.read_csv('HR_comma_sep.csv')

data.head()

,satisfaction_level,last_evaluation,number_project,average_montly_hours,time_spend_company,Work_accident,left,promotion_last_5years,sales,salary
0,0.38,0.53,2,157,3,0,1,0,sales,low
1,0.80,0.86,5,262,6,0,1,0,sales,medium
2,0.11,0.88,7,272,4,0,1,0,sales,medium
3,0.72,0.87,5,223,5,0,1,0,sales,low
4,0.37,0.52,2,159,3,0,1,0,sales,low

In [24]:
# Import LabelEncoder
from sklearn import preprocessing

# Creating labelEncoder
le = preprocessing.LabelEncoder()

In [26]:
# Spliting data into Feature and
X=data[['satisfaction_level', 'last_evaluation', 'number_project', 'average_montly_hours', 'time_spend_company', 'Work_accident', 'promotion_last_5years','salary']]
y=data['left']

# Import train_test_split function
from sklearn.model_selection import train_test_split

# Split dataset into training set and test set
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=42)  # 70% training and 30% test

In [27]:
# Import MLPClassifer 
from sklearn.neural_network import MLPClassifier

# Create model object
clf = MLPClassifier(hidden_layer_sizes=(6,5),
                    random_state=5,
                    verbose=True,
                    learning_rate_init=0.01)

# Fit data onto the model
clf.fit(X_train,y_train)

Iteration 1, loss = 0.58375699
Iteration 2, loss = 0.55089476
Iteration 3, loss = 0.53811793
Iteration 4, loss = 0.51521772
Iteration 5, loss = 0.50091513
Iteration 6, loss = 0.50279914
Iteration 7, loss = 0.47967376
Iteration 8, loss = 0.48207220
Iteration 9, loss = 0.48021354
Iteration 10, loss = 0.47412735
Iteration 11, loss = 0.47203837
Iteration 12, loss = 0.46928072
Iteration 13, loss = 0.45686180
Iteration 14, loss = 0.45709884
Iteration 15, loss = 0.45132223
Iteration 16, loss = 0.46630415
Iteration 17, loss = 0.45162435
Iteration 18, loss = 0.46152781
Iteration 19, loss = 0.45317280
Iteration 20, loss = 0.45251283
Iteration 21, loss = 0.46049935
Iteration 22, loss = 0.45274210
Iteration 23, loss = 0.45780399
Iteration 24, loss = 0.45557925
Iteration 25, loss = 0.45298486
Iteration 26, loss = 0.44800479
Iteration 27, loss = 0.44150279
Iteration 28, loss = 0.43542267
Iteration 29, loss = 0.42998854
Iteration 30, loss = 0.45012144
Iteration 31, loss = 0.43029912
Iteration 32, loss = 0.43634880
Iteration 33, loss = 0.40753539
Iteration 34, loss = 0.38134546
Iteration 35, loss = 0.37172246
Iteration 36, loss = 0.31251239
Iteration 37, loss = 0.28918613
Iteration 38, loss = 0.28283210
Iteration 39, loss = 0.27833283
Iteration 40, loss = 0.27272805
Iteration 41, loss = 0.27923282
Iteration 42, loss = 0.26109321
Iteration 43, loss = 0.26094732
Iteration 44, loss = 0.27726581
Iteration 45, loss = 0.27587586
Iteration 46, loss = 0.26246829
Iteration 47, loss = 0.25809416
Iteration 48, loss = 0.25485387
Iteration 49, loss = 0.26039751
Iteration 50, loss = 0.25603374
Iteration 51, loss = 0.25442411
Iteration 52, loss = 0.26750719
Iteration 53, loss = 0.25383941
Iteration 54, loss = 0.26890198
Iteration 55, loss = 0.25243726
Iteration 56, loss = 0.24835140
Iteration 57, loss = 0.25112074
Iteration 58, loss = 0.26393526
Iteration 59, loss = 0.24959074
Iteration 60, loss = 0.24945577
Iteration 61, loss = 0.25030818
Iteration 62, loss = 0.24482235
Iteration 63, loss = 0.24760731
Iteration 64, loss = 0.24232444
Iteration 65, loss = 0.25120470
Iteration 66, loss = 0.23956221
Iteration 67, loss = 0.24070583
Iteration 68, loss = 0.24001137
Iteration 69, loss = 0.24213452
Iteration 70, loss = 0.24363731
Iteration 71, loss = 0.24133572
Iteration 72, loss = 0.24019882
Iteration 73, loss = 0.25667863
Iteration 74, loss = 0.24141876
Iteration 75, loss = 0.24045123
Iteration 76, loss = 0.24324913
Iteration 77, loss = 0.24052475
Training loss did not improve more than tol=0.000100 for 10 consecutive epochs. Stopping.

MLPClassifier(hidden_layer_sizes=(6, 5), learning_rate_init=0.01,
              random_state=5, verbose=True)

In [28]:
# Make prediction on test dataset
ypred=clf.predict(X_test)

# Import accuracy score 
from sklearn.metrics import accuracy_score

# Calcuate accuracy
accuracy_score(y_test,ypred)

0.9148888888888889